CREATE TABLE IF NOT EXISTS `ypay_order_callback_task` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_key` varchar(160) NOT NULL,
  `order_id` int(11) NOT NULL,
  `merchant_id` int(11) NOT NULL DEFAULT '0',
  `trade_no` varchar(64) DEFAULT NULL,
  `out_trade_no` varchar(64) DEFAULT NULL,
  `scene` varchar(32) NOT NULL DEFAULT 'settlement',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `attempt_count` int(11) NOT NULL DEFAULT '0',
  `max_attempts` int(11) NOT NULL DEFAULT '8',
  `next_run_at` datetime DEFAULT NULL,
  `locked_at` datetime DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `notify_url` text,
  `return_url` text,
  `callback_url` text,
  `payload_json` longtext,
  `last_http_status` int(11) DEFAULT NULL,
  `last_error` text,
  `last_response_body` longtext,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_task_key` (`task_key`),
  KEY `idx_status_next_run` (`status`,`next_run_at`),
  KEY `idx_order_scene` (`order_id`,`scene`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ypay_order_reconcile_task` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_key` varchar(160) NOT NULL,
  `order_id` int(11) NOT NULL,
  `merchant_id` int(11) NOT NULL DEFAULT '0',
  `account_id` int(11) NOT NULL DEFAULT '0',
  `trade_no` varchar(64) DEFAULT NULL,
  `out_trade_no` varchar(64) DEFAULT NULL,
  `plugin_code` varchar(64) NOT NULL DEFAULT '',
  `channel_code` varchar(64) NOT NULL DEFAULT '',
  `payment_type` varchar(32) DEFAULT NULL,
  `query_identifier` varchar(255) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `attempt_count` int(11) NOT NULL DEFAULT '0',
  `max_attempts` int(11) NOT NULL DEFAULT '30',
  `next_run_at` datetime DEFAULT NULL,
  `locked_at` datetime DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `last_error` text,
  `last_result_json` longtext,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_task_key` (`task_key`),
  KEY `idx_status_next_run` (`status`,`next_run_at`),
  KEY `idx_plugin_status` (`plugin_code`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
