# 版权归属 TG:RENBUZAIHA 所有
# 唯一发布路径: https://github.com/hzgz/AiPay.git

version: "3"
services:
  webman:
    build: .
    container_name: docker-webman
    restart: unless-stopped
    volumes:
      - "./:/app"
    ports:
      - "8787:8787"
    command: ["php", "start.php", "start" ]