# 版权归属 TG:RENBUZAIHA 所有
# 唯一发布路径: https://github.com/hzgz/AiPay.git

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  core-js: true
  es5-ext: true
  esbuild: true
  vue-demi: true
